# Generated by Django 2.2.12 on 2021-11-24 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_auto_20211123_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitems',
            name='sub_total',
            field=models.IntegerField(null=True),
        ),
    ]
