# Generated by Django 2.2.12 on 2021-12-03 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0004_cartitems_sub_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitems',
            old_name='product',
            new_name='products_id',
        ),
        migrations.RemoveField(
            model_name='cartitems',
            name='sub_total',
        ),
    ]
