# Generated by Django 2.2.12 on 2021-12-04 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0006_auto_20211204_0522'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitems',
            old_name='products',
            new_name='product',
        ),
    ]
