# Generated by Django 2.2.12 on 2021-12-13 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0007_auto_20211204_0524'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitems',
            name='grand_total',
            field=models.IntegerField(null=True),
        ),
    ]
