# Generated by Django 2.2.12 on 2021-12-13 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0008_cartitems_grand_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitems',
            name='grand_total',
        ),
    ]
