# Generated by Django 2.2.12 on 2021-12-14 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0009_remove_cartitems_grand_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitems',
            name='anonymous_user',
        ),
    ]
