# Generated by Django 2.2.12 on 2021-12-21 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0011_wishcart_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitems',
            name='cart',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
