# Generated by Django 2.2.12 on 2021-11-18 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_order_orderitem_shippingaddress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='customer',
            new_name='first_name',
        ),
    ]
