# Generated by Django 2.2.12 on 2021-12-01 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0009_auto_20211123_1350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='title',
        ),
        migrations.RemoveField(
            model_name='categories',
            name='url_slug',
        ),
        migrations.AddField(
            model_name='categories',
            name='cat_image',
            field=models.ImageField(blank=True, upload_to='pics/categories'),
        ),
        migrations.AddField(
            model_name='categories',
            name='category_name',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='categories',
            name='slug',
            field=models.SlugField(max_length=100, null=True, unique=True),
        ),
    ]
