# Generated by Django 2.2.12 on 2021-12-06 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0012_auto_20211201_0846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='in_stock_total',
        ),
        migrations.AddField(
            model_name='products',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='products',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='products',
            name='stock',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='url_slug',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
