# Generated by Django 2.2.12 on 2021-12-08 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0014_products_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_name', models.CharField(max_length=100, null=True)),
                ('offer_percent', models.IntegerField()),
                ('expiry_date', models.DateField()),
                ('expiry_time', models.TimeField()),
                ('offer_status', models.CharField(default=True, max_length=100)),
            ],
        ),
    ]
