# Generated by Django 2.2.12 on 2021-12-09 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0015_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='offer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='category.Offer'),
        ),
    ]
