# Generated by Django 2.2.12 on 2021-12-09 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0016_categories_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='expiry_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='expiry_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='offer_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='offer_percent',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='offer_type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
