# Generated by Django 2.2.12 on 2021-12-22 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0022_auto_20211222_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='brand',
            field=models.CharField(max_length=100),
        ),
    ]
