# Generated by Django 2.2.12 on 2022-01-02 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0024_auto_20211222_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_max_price',
            field=models.IntegerField(),
        ),
    ]
