# Generated by Django 2.2.12 on 2021-11-22 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20211122_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='user_address',
            field=models.CharField(max_length=2500, null=True),
        ),
    ]
