# Generated by Django 2.2.12 on 2021-11-23 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_orderproduct_payment_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='payment_mode',
        ),
        migrations.AddField(
            model_name='orders',
            name='payment_mode',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
