# Generated by Django 2.2.12 on 2021-11-23 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20211123_0559'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderproduct',
            old_name='product_price',
            new_name='grand_total',
        ),
    ]
