# Generated by Django 2.2.12 on 2021-11-23 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20211123_0633'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='tax',
            field=models.FloatField(null=True),
        ),
    ]
