# Generated by Django 2.2.12 on 2021-11-24 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_auto_20211124_0658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitems',
            name='sub_total',
            field=models.IntegerField(null=True),
        ),
    ]
