# Generated by Django 2.2.12 on 2021-11-24 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_auto_20211124_0702'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='grand_total',
            field=models.IntegerField(null=True),
        ),
    ]
