# Generated by Django 2.2.12 on 2021-12-15 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_auto_20211203_1324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitems',
            name='anonymous_user',
        ),
    ]
