# Generated by Django 2.2.12 on 2021-12-31 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_remove_orderitems_anonymous_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='delivery_status',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
